services:
  - type: web
    name: icms-backend
    runtime: java
    region: singapore
    plan: free
    buildCommand: cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar backend/target/icms-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
      - key: JAVA_VERSION
        value: "17"
