services:
  - type: web
    name: icms-backend
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
      - key: PORT
        value: "8080"
