services:
  - type: web
    name: icms-backend
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: PORT
        value: "8080"

databases:
  - name: icms-db
    region: singapore
    plan: free
    databaseName: icmsdb
    user: icmsuser
